{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Election Results\n",
      "--------------------------\n",
      "Total Votes: 3521001\n",
      "Khan: 63.0% (2218231)\n",
      "Correy: 20.0% (704200)\n",
      "Li: 14.0% (492940)\n",
      "O'Tooley: 3.0% (105630)\n",
      "---------------------------\n",
      "Winner: Khan\n",
      "---------------------------\n",
      "Election Results\n",
      "--------------------------\n",
      "Total Votes: 7042002\n",
      "Khan: 63.0% (4436462)\n",
      "Correy: 20.0% (1408400)\n",
      "Li: 14.0% (985880)\n",
      "O'Tooley: 3.0% (211260)\n",
      "---------------------------\n",
      "Winner: Khan\n",
      "---------------------------\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import csv\n",
    "\n",
    "# Create variables \n",
    "candidates = []\n",
    "num_votes = 0\n",
    "vote_counts = []\n",
    "\n",
    "# List of files \n",
    "election_data = ['1', '2']\n",
    "\n",
    "# Loop through files\n",
    "for files in election_data:\n",
    "    # Get CSV\n",
    "    election_dataCSV = os.path.join(\"Resources/election_data.csv\")\n",
    "\n",
    "    # Open current CSV\n",
    "    with open(election_dataCSV) as csvFile:\n",
    "\n",
    "        csvReader = csv.reader(csvFile, delimiter=',')\n",
    "\n",
    "        # Skip headers\n",
    "        line = next(csvReader,None)\n",
    "\n",
    "        # Process the votes\n",
    "        for line in csvReader:\n",
    "\n",
    "            # Add to total number of votes\n",
    "            num_votes = num_votes + 1\n",
    "\n",
    "            # The candidate voted for\n",
    "            candidate = line[2]\n",
    "\n",
    "            # If the candidate has other votes then add to vote total\n",
    "            if candidate in candidates:\n",
    "                candidate_index = candidates.index(candidate)\n",
    "                vote_counts[candidate_index] = vote_counts[candidate_index] + 1\n",
    "            # Else create new spot in list for candidate\n",
    "            else:\n",
    "                candidates.append(candidate)\n",
    "                vote_counts.append(1)\n",
    "\n",
    "    # Create variables for calculations\n",
    "    percentages = []\n",
    "    max_votes = vote_counts[0]\n",
    "    max_index = 0\n",
    "\n",
    "    # Percentage of vote for each candidate and the winner\n",
    "    for count in range(len(candidates)):\n",
    "        vote_percentage = vote_counts[count]/num_votes*100\n",
    "        percentages.append(vote_percentage)\n",
    "        if vote_counts[count] > max_votes:\n",
    "            max_votes = vote_counts[count]\n",
    "            print(max_votes)\n",
    "            max_index = count\n",
    "    winner = candidates[max_index]\n",
    "\n",
    "    # Round decimal\n",
    "\n",
    "    percentages = [round(i,2) for i in percentages]\n",
    "\n",
    "    # Print results\n",
    "    print(\"Election Results\")\n",
    "    print(\"--------------------------\")\n",
    "    print(f\"Total Votes: {num_votes}\")\n",
    "    for count in range(len(candidates)):\n",
    "        print(f\"{candidates[count]}: {percentages[count]}% ({vote_counts[count]})\")\n",
    "    print(\"---------------------------\")\n",
    "    print(f\"Winner: {winner}\")\n",
    "    print(\"---------------------------\")\n",
    "\n",
    "    # Name white file\n",
    "    output_file = election_dataCSV[0:-4]\n",
    "\n",
    "    write_election_dataCSV = f\"{output_file}pypoll_results.txt\"\n",
    "\n",
    "    # Open write file\n",
    "    filewriter = open(write_election_dataCSV, mode = 'w')\n",
    "\n",
    "    # Print to write file\n",
    "    filewriter.write(\"Election Results\\n\")\n",
    "    filewriter.write(\"--------------------------\\n\")\n",
    "    filewriter.write(f\"Total Votes: {num_votes}\\n\")\n",
    "    for count in range(len(candidates)):\n",
    "        filewriter.write(f\"{candidates[count]}: {percentages[count]}% ({vote_counts[count]})\\n\")\n",
    "    filewriter.write(\"---------------------------\\n\")\n",
    "    filewriter.write(f\"Winner: {winner}\\n\")\n",
    "    filewriter.write(\"---------------------------\\n\")\n",
    "\n",
    "    # Close file\n",
    "    filewriter.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
